### ISSUE TITLE
phonenumbers.parse failed for Iranian phone numbers with country code +96

### ISSUE THREAD

**Issue by clpun0702** [daviddrysdale/python-phonenumbers#162]
It seems that Iranian phone numbers with country code +96 cannot be recognized: 

```
>>> phonenumbers.parse("+96-990-555-8499", "IR")
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/phonenumbers/phonenumberutil.py", line 2827, in parse
    numobj)
  File "/usr/local/lib/python3.6/site-packages/phonenumbers/phonenumberutil.py", line 2517, in _maybe_extract_country_code
    "Country calling code supplied was not recognised.")
phonenumbers.phonenumberutil.NumberParseException: (0) Country calling code supplied was not recognised.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/phonenumbers/phonenumberutil.py", line 2840, in parse
    "Could not interpret numbers after plus-sign.")
phonenumbers.phonenumberutil.NumberParseException: (0) Could not interpret numbers after plus-sign.
```

**Comment by daviddrysdale** [comment]
Looks like the [upstream code does something similar](https://libphonenumber.appspot.com/phonenumberparser?number=%2B96-990-555-8499&country=IR):
```
Phone Number entered: +96-990-555-8499
defaultCountry entered: IR
Language entered: en
Error type: INVALID_COUNTRY_CODE. Could not interpret numbers after plus-sign.
```
so this is best raised upstream.  (However, I'd guess that +969 is not a valid [country calling code](https://en.wikipedia.org/wiki/List_of_country_calling_codes#Zone_9:_mostly_southern_Asia))
