### ISSUE TITLE
Not working for Nigeria Phone Numbers

### ISSUE THREAD

**Issue by alifa2try** [daviddrysdale/python-phonenumbers#175]
I ran into this error with Nigeria phone number : 

```
Traceback (most recent call last):
  File "phone.py", line 5, in <module>
    processed_number = phonenumbers.parse('number', 'NG')
  File "/usr/local/lib/python3.8/dist-packages/phonenumbers/phonenumberutil.py", line 2800, in parse
    raise NumberParseException(NumberParseException.NOT_A_NUMBER,
phonenumbers.phonenumberutil.NumberParseException: (1) The string supplied did not seem to be a phone number.
```

**Comment by daviddrysdale** [comment]
The first argument to `parse` is quoted, so it will be treated as a string ("number").  Did you intend to have `phonenumbers.parse(number, 'NG')` (with unquoted `number` being a variable name from your program)?
