### ISSUE TITLE
ModuleNotFoundError: No module named 'phonenumber_field'

### ISSUE THREAD

**Issue by siddeshpawar** [daviddrysdale/python-phonenumbers#190]
######ERROR######
(XYZLO_ve) C:\siddesh\Personal\XYZLO_VERSIONING\XYZLO_VERSIONING_1\blankabotzxyzlo\Xyzlo>python manage.py makemigrations
Traceback (most recent call last):
  File "C:\siddesh\Personal\XYZLO_VERSIONING\XYZLO_VERSIONING_1\blankabotzxyzlo\Xyzlo\manage.py", line 22, in <module>
    main()
  File "C:\siddesh\Personal\XYZLO_VERSIONING\XYZLO_VERSIONING_1\blankabotzxyzlo\Xyzlo\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\sidde\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\sidde\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\sidde\AppData\Local\Programs\Python\Python39\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\sidde\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\sidde\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\sidde\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'phonenumber_field'

############################
When ever i am trying to do migration i am facing this issue. where as all the mentioned libraries are installed properly also added in installed app list. please unpdate me the bug solver. i had tried every thing but i hope i might have missed the pin in the sand.

**Comment by daviddrysdale** [comment]
This library is completely independent of Django, so I think you're asking for help in the wrong place I'm afraid.
