### ISSUE TITLE
[Installation via pip in virtualenv] ImportError: No module named shortdata

### ISSUE THREAD

**Issue by ymage** [daviddrysdale/python-phonenumbers#23]
```
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/home/userdev/envs/userproject/build/phonenumbers/setup.py", line 40, in <module>
    from phonenumbers import __version__
  File "phonenumbers/__init__.py", line 79, in <module>
    from .asyoutypeformatter import AsYouTypeFormatter
  File "phonenumbers/asyoutypeformatter.py", line 32, in <module>
    from .phonenumberutil import _VALID_PUNCTUATION, REGION_CODE_FOR_NON_GEO_ENTITY
  File "phonenumbers/phonenumberutil.py", line 44, in <module>
    from .shortdata import _AVAILABLE_REGION_CODES as _AVAILABLE_SHORT_REGION_CODES
ImportError: No module named shortdata
```

**Comment by daviddrysdale** [comment]
Sorry, forgot to update setup.py for new sub-package.  Try now.

**Comment by sethlivingston** [comment]
Same error in the P3 branch. Are we just missing a merge? (And thank you for creating and maintaining the P3 branch.)

**Comment by daviddrysdale** [comment]
Hmm, the relevant commit did get merged across into the `python3` branch (in commit ae830800174e1132cc5ee47374543831974bdbdc).  What's the precise command you're invoking with?

**Comment by daviddrysdale** [comment]
Doh, forgot there's a top-level `setup.py` for pip as well as the one in `python/`.  Try now.

**Comment by sethlivingston** [comment]
Thanks, David!
