### ISSUE TITLE
phonenumber.parse fails even though number is valid - 17748019715

### ISSUE THREAD

**Issue by ShacharRatzabi** [daviddrysdale/python-phonenumbers#300]
python 3.11.6
phonenumbers 8.13.42

We are a company that provides workforce management for deskless employees, most of our users are mobile-users, and we have a user that can't login using the following number: `+17748019715`

Tried to analyze the issue and saw that it fails on this error:
```
In [1]: import phonenumbers

In [2]: phone_number = '1774801975'

In [3]: parsed_phone_number = phonenumbers.parse(phone_number)
---------------------------------------------------------------------------
NumberParseException                      Traceback (most recent call last)
Cell In[3], line 1
----> 1 parsed_phone_number = phonenumbers.parse(phone_number)

File ***/venv/lib/python3.11/site-packages/phonenumbers/phonenumberutil.py:2948, in parse(number, region, keep_raw_input, numobj, _check_region)
   2945 # Check the region supplied is valid, or that the extracted number starts
   2946 # with some sort of + sign so the number's region can be determined.
   2947 if _check_region and not _check_region_for_parsing(national_number, region):
-> 2948     raise NumberParseException(NumberParseException.INVALID_COUNTRY_CODE,
   2949                                "Missing or invalid default region.")
   2950 if keep_raw_input:
   2951     numobj.raw_input = number

NumberParseException: (0) Missing or invalid default region.
```
![image](https://github.com/user-attachments/assets/008ef4b1-5e9c-4750-b036-2f9c3ce3137e)

Number seems to be valid

**Expected:**
should pass parsing and identify this number as 7748019715 and the region as +1 (United States), as we do have a customer that have this phone number.

can you help us to fix this issue? this user cannot login our system

**Comment by daviddrysdale** [comment]
Need either the leading + or a region.
```pycon
>>> import phonenumbers
>>> x = phonenumbers.parse("1774801975")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dmd/src/python-phonenumbers/python/phonenumbers/phonenumberutil.py", line 2948, in parse
    raise NumberParseException(NumberParseException.INVALID_COUNTRY_CODE,
phonenumbers.phonenumberutil.NumberParseException: (0) Missing or invalid default region.
>>> x = phonenumbers.parse("+1774801975")
>>> x = phonenumbers.parse("1774801975", "US")
```
